const future = {
  "location": {
    "name": "Saint-Merri",
    "region": "Ile-de-France",
    "country": "France",
    "lat": 48.86,
    "lon": 2.35,
    "tz_id": "Europe/Paris",
    "localtime_epoch": 1654475777,
    "localtime": "2022-06-06 2:36"
  },
  "current": {
    "last_updated_epoch": 1654475400,
    "last_updated": "2022-06-06 02:30",
    "temp_c": 15,
    "temp_f": 59,
    "is_day": 0,
    "condition": {
      "text": "Parcialmente nublado",
      "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
      "code": 1003
    },
    "wind_mph": 3.8,
    "wind_kph": 6.1,
    "wind_degree": 220,
    "wind_dir": "SW",
    "pressure_mb": 1018,
    "pressure_in": 30.06,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 94,
    "cloud": 25,
    "feelslike_c": 14.5,
    "feelslike_f": 58.1,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 1,
    "gust_mph": 11.6,
    "gust_kph": 18.7
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2022-06-06",
        "date_epoch": 1654473600,
        "day": {
          "maxtemp_c": 22,
          "maxtemp_f": 71.6,
          "mintemp_c": 11.5,
          "mintemp_f": 52.7,
          "avgtemp_c": 16.6,
          "avgtemp_f": 61.9,
          "maxwind_mph": 11,
          "maxwind_kph": 17.6,
          "totalprecip_mm": 0.3,
          "totalprecip_in": 0.01,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 64,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 83,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Lluvia  moderada a intervalos",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 7
        },
        "astro": {
          "sunrise": "05:49 AM",
          "sunset": "09:50 PM",
          "moonrise": "12:00 PM",
          "moonset": "02:20 AM",
          "moon_phase": "First Quarter",
          "moon_illumination": "46"
        },
        "hour": [
          {
            "time_epoch": 1654466400,
            "time": "2022-06-06 00:00",
            "temp_c": 14,
            "temp_f": 57.2,
            "is_day": 0,
            "condition": {
              "text": "Lluvia  moderada a intervalos",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 237,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 73,
            "feelslike_c": 13.5,
            "feelslike_f": 56.3,
            "windchill_c": 13.5,
            "windchill_f": 56.3,
            "heatindex_c": 14,
            "heatindex_f": 57.2,
            "dewpoint_c": 10.8,
            "dewpoint_f": 51.4,
            "will_it_rain": 1,
            "chance_of_rain": 74,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 1
          },
          {
            "time_epoch": 1654470000,
            "time": "2022-06-06 01:00",
            "temp_c": 13.4,
            "temp_f": 56.1,
            "is_day": 0,
            "condition": {
              "text": "Despejado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 238,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 10,
            "feelslike_c": 12.6,
            "feelslike_f": 54.7,
            "windchill_c": 12.6,
            "windchill_f": 54.7,
            "heatindex_c": 13.4,
            "heatindex_f": 56.1,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 1
          },
          {
            "time_epoch": 1654473600,
            "time": "2022-06-06 02:00",
            "temp_c": 13,
            "temp_f": 55.4,
            "is_day": 0,
            "condition": {
              "text": "Despejado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 244,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 23,
            "feelslike_c": 12.1,
            "feelslike_f": 53.8,
            "windchill_c": 12.1,
            "windchill_f": 53.8,
            "heatindex_c": 13,
            "heatindex_f": 55.4,
            "dewpoint_c": 9.6,
            "dewpoint_f": 49.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.4,
            "gust_kph": 18.4,
            "uv": 1
          },
          {
            "time_epoch": 1654477200,
            "time": "2022-06-06 03:00",
            "temp_c": 12.5,
            "temp_f": 54.5,
            "is_day": 0,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 247,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 33,
            "feelslike_c": 11.6,
            "feelslike_f": 52.9,
            "windchill_c": 11.6,
            "windchill_f": 52.9,
            "heatindex_c": 12.5,
            "heatindex_f": 54.5,
            "dewpoint_c": 9.1,
            "dewpoint_f": 48.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 1
          },
          {
            "time_epoch": 1654480800,
            "time": "2022-06-06 04:00",
            "temp_c": 11.9,
            "temp_f": 53.4,
            "is_day": 0,
            "condition": {
              "text": "Despejado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 244,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.05,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 14,
            "feelslike_c": 10.9,
            "feelslike_f": 51.6,
            "windchill_c": 10.9,
            "windchill_f": 51.6,
            "heatindex_c": 11.9,
            "heatindex_f": 53.4,
            "dewpoint_c": 8.6,
            "dewpoint_f": 47.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.5,
            "gust_kph": 16.9,
            "uv": 1
          },
          {
            "time_epoch": 1654484400,
            "time": "2022-06-06 05:00",
            "temp_c": 11.5,
            "temp_f": 52.7,
            "is_day": 0,
            "condition": {
              "text": "Despejado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 236,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 6,
            "feelslike_c": 10.5,
            "feelslike_f": 50.9,
            "windchill_c": 10.5,
            "windchill_f": 50.9,
            "heatindex_c": 11.5,
            "heatindex_f": 52.7,
            "dewpoint_c": 8.4,
            "dewpoint_f": 47.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 1
          },
          {
            "time_epoch": 1654488000,
            "time": "2022-06-06 06:00",
            "temp_c": 11.8,
            "temp_f": 53.2,
            "is_day": 1,
            "condition": {
              "text": "Soleado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 232,
            "wind_dir": "SW",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 13,
            "feelslike_c": 10.7,
            "feelslike_f": 51.3,
            "windchill_c": 10.7,
            "windchill_f": 51.3,
            "heatindex_c": 11.8,
            "heatindex_f": 53.2,
            "dewpoint_c": 8.4,
            "dewpoint_f": 47.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 4
          },
          {
            "time_epoch": 1654491600,
            "time": "2022-06-06 07:00",
            "temp_c": 13,
            "temp_f": 55.4,
            "is_day": 1,
            "condition": {
              "text": "Soleado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 245,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 6,
            "feelslike_c": 11.8,
            "feelslike_f": 53.2,
            "windchill_c": 11.8,
            "windchill_f": 53.2,
            "heatindex_c": 13,
            "heatindex_f": 55.4,
            "dewpoint_c": 8.7,
            "dewpoint_f": 47.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 4
          },
          {
            "time_epoch": 1654495200,
            "time": "2022-06-06 08:00",
            "temp_c": 14.7,
            "temp_f": 58.5,
            "is_day": 1,
            "condition": {
              "text": "Soleado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 248,
            "wind_dir": "WSW",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 68,
            "cloud": 10,
            "feelslike_c": 13.7,
            "feelslike_f": 56.7,
            "windchill_c": 13.7,
            "windchill_f": 56.7,
            "heatindex_c": 14.7,
            "heatindex_f": 58.5,
            "dewpoint_c": 8.8,
            "dewpoint_f": 47.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11,
            "gust_kph": 17.6,
            "uv": 4
          },
          {
            "time_epoch": 1654498800,
            "time": "2022-06-06 09:00",
            "temp_c": 16.3,
            "temp_f": 61.3,
            "is_day": 1,
            "condition": {
              "text": "Soleado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 245,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 60,
            "cloud": 8,
            "feelslike_c": 16.3,
            "feelslike_f": 61.3,
            "windchill_c": 16.3,
            "windchill_f": 61.3,
            "heatindex_c": 16.3,
            "heatindex_f": 61.3,
            "dewpoint_c": 8.4,
            "dewpoint_f": 47.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.4,
            "gust_kph": 18.4,
            "uv": 5
          },
          {
            "time_epoch": 1654502400,
            "time": "2022-06-06 10:00",
            "temp_c": 17.6,
            "temp_f": 63.7,
            "is_day": 1,
            "condition": {
              "text": "Soleado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 246,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 54,
            "cloud": 7,
            "feelslike_c": 17.6,
            "feelslike_f": 63.7,
            "windchill_c": 17.6,
            "windchill_f": 63.7,
            "heatindex_c": 17.6,
            "heatindex_f": 63.7,
            "dewpoint_c": 8.2,
            "dewpoint_f": 46.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.1,
            "gust_kph": 19.4,
            "uv": 5
          },
          {
            "time_epoch": 1654506000,
            "time": "2022-06-06 11:00",
            "temp_c": 18.9,
            "temp_f": 66,
            "is_day": 1,
            "condition": {
              "text": "Nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 248,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 50,
            "cloud": 70,
            "feelslike_c": 18.9,
            "feelslike_f": 66,
            "windchill_c": 18.9,
            "windchill_f": 66,
            "heatindex_c": 18.9,
            "heatindex_f": 66,
            "dewpoint_c": 8.2,
            "dewpoint_f": 46.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.5,
            "gust_kph": 20.2,
            "uv": 4
          },
          {
            "time_epoch": 1654509600,
            "time": "2022-06-06 12:00",
            "temp_c": 20,
            "temp_f": 68,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 247,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 46,
            "cloud": 35,
            "feelslike_c": 20,
            "feelslike_f": 68,
            "windchill_c": 20,
            "windchill_f": 68,
            "heatindex_c": 20,
            "heatindex_f": 68,
            "dewpoint_c": 7.9,
            "dewpoint_f": 46.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.3,
            "gust_kph": 19.8,
            "uv": 6
          },
          {
            "time_epoch": 1654513200,
            "time": "2022-06-06 13:00",
            "temp_c": 21,
            "temp_f": 69.8,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 246,
            "wind_dir": "WSW",
            "pressure_mb": 1018,
            "pressure_in": 30.05,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 42,
            "cloud": 49,
            "feelslike_c": 21,
            "feelslike_f": 69.8,
            "windchill_c": 21,
            "windchill_f": 69.8,
            "heatindex_c": 21,
            "heatindex_f": 69.8,
            "dewpoint_c": 7.7,
            "dewpoint_f": 45.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.1,
            "gust_kph": 19.4,
            "uv": 6
          },
          {
            "time_epoch": 1654516800,
            "time": "2022-06-06 14:00",
            "temp_c": 21.7,
            "temp_f": 71.1,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 242,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 41,
            "cloud": 44,
            "feelslike_c": 21.7,
            "feelslike_f": 71.1,
            "windchill_c": 21.7,
            "windchill_f": 71.1,
            "heatindex_c": 24,
            "heatindex_f": 75.2,
            "dewpoint_c": 7.8,
            "dewpoint_f": 46,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 6
          },
          {
            "time_epoch": 1654520400,
            "time": "2022-06-06 15:00",
            "temp_c": 22,
            "temp_f": 71.6,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 240,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 40,
            "cloud": 45,
            "feelslike_c": 24,
            "feelslike_f": 75.2,
            "windchill_c": 22,
            "windchill_f": 71.6,
            "heatindex_c": 24,
            "heatindex_f": 75.2,
            "dewpoint_c": 8,
            "dewpoint_f": 46.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 6
          },
          {
            "time_epoch": 1654524000,
            "time": "2022-06-06 16:00",
            "temp_c": 21.7,
            "temp_f": 71.1,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 240,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 43,
            "cloud": 47,
            "feelslike_c": 21.7,
            "feelslike_f": 71.1,
            "windchill_c": 21.7,
            "windchill_f": 71.1,
            "heatindex_c": 24.1,
            "heatindex_f": 75.4,
            "dewpoint_c": 8.4,
            "dewpoint_f": 47.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 6
          },
          {
            "time_epoch": 1654527600,
            "time": "2022-06-06 17:00",
            "temp_c": 21.2,
            "temp_f": 70.2,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 8.7,
            "wind_kph": 14,
            "wind_degree": 238,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 46,
            "cloud": 45,
            "feelslike_c": 21.2,
            "feelslike_f": 70.2,
            "windchill_c": 21.2,
            "windchill_f": 70.2,
            "heatindex_c": 24.2,
            "heatindex_f": 75.6,
            "dewpoint_c": 9.2,
            "dewpoint_f": 48.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 6
          },
          {
            "time_epoch": 1654531200,
            "time": "2022-06-06 18:00",
            "temp_c": 20.2,
            "temp_f": 68.4,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 237,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 53,
            "cloud": 47,
            "feelslike_c": 20.2,
            "feelslike_f": 68.4,
            "windchill_c": 20.2,
            "windchill_f": 68.4,
            "heatindex_c": 20.2,
            "heatindex_f": 68.4,
            "dewpoint_c": 10.3,
            "dewpoint_f": 50.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 6
          },
          {
            "time_epoch": 1654534800,
            "time": "2022-06-06 19:00",
            "temp_c": 18.8,
            "temp_f": 65.8,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 237,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 62,
            "cloud": 58,
            "feelslike_c": 18.8,
            "feelslike_f": 65.8,
            "windchill_c": 18.8,
            "windchill_f": 65.8,
            "heatindex_c": 18.8,
            "heatindex_f": 65.8,
            "dewpoint_c": 11.3,
            "dewpoint_f": 52.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 5
          },
          {
            "time_epoch": 1654538400,
            "time": "2022-06-06 20:00",
            "temp_c": 16.8,
            "temp_f": 62.2,
            "is_day": 1,
            "condition": {
              "text": "Lluvia  moderada a intervalos",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 244,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 73,
            "cloud": 100,
            "feelslike_c": 16.8,
            "feelslike_f": 62.2,
            "windchill_c": 16.8,
            "windchill_f": 62.2,
            "heatindex_c": 16.8,
            "heatindex_f": 62.2,
            "dewpoint_c": 11.9,
            "dewpoint_f": 53.4,
            "will_it_rain": 0,
            "chance_of_rain": 63,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 4
          },
          {
            "time_epoch": 1654542000,
            "time": "2022-06-06 21:00",
            "temp_c": 15.9,
            "temp_f": 60.6,
            "is_day": 1,
            "condition": {
              "text": "Nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 253,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.04,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 65,
            "feelslike_c": 15.9,
            "feelslike_f": 60.6,
            "windchill_c": 15.9,
            "windchill_f": 60.6,
            "heatindex_c": 15.9,
            "heatindex_f": 60.6,
            "dewpoint_c": 11.5,
            "dewpoint_f": 52.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.9,
            "gust_kph": 19.1,
            "uv": 4
          },
          {
            "time_epoch": 1654545600,
            "time": "2022-06-06 22:00",
            "temp_c": 15.7,
            "temp_f": 60.3,
            "is_day": 0,
            "condition": {
              "text": "Lluvia  moderada a intervalos",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 246,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.04,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 100,
            "feelslike_c": 15.7,
            "feelslike_f": 60.3,
            "windchill_c": 15.7,
            "windchill_f": 60.3,
            "heatindex_c": 15.7,
            "heatindex_f": 60.3,
            "dewpoint_c": 11.3,
            "dewpoint_f": 52.3,
            "will_it_rain": 1,
            "chance_of_rain": 83,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 1
          },
          {
            "time_epoch": 1654549200,
            "time": "2022-06-06 23:00",
            "temp_c": 15.6,
            "temp_f": 60.1,
            "is_day": 0,
            "condition": {
              "text": "Cielo cubierto",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 241,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 100,
            "feelslike_c": 15.6,
            "feelslike_f": 60.1,
            "windchill_c": 15.6,
            "windchill_f": 60.1,
            "heatindex_c": 15.6,
            "heatindex_f": 60.1,
            "dewpoint_c": 11.2,
            "dewpoint_f": 52.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 1
          }
        ]
      },
      {
        "date": "2022-06-07",
        "date_epoch": 1654560000,
        "day": {
          "maxtemp_c": 21.9,
          "maxtemp_f": 71.4,
          "mintemp_c": 14,
          "mintemp_f": 57.2,
          "avgtemp_c": 16.9,
          "avgtemp_f": 62.5,
          "maxwind_mph": 11,
          "maxwind_kph": 17.6,
          "totalprecip_mm": 2.5,
          "totalprecip_in": 0.1,
          "avgvis_km": 9.5,
          "avgvis_miles": 5,
          "avghumidity": 77,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 87,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Lluvia  moderada a intervalos",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 6
        },
        "astro": {
          "sunrise": "05:48 AM",
          "sunset": "09:51 PM",
          "moonrise": "01:12 PM",
          "moonset": "02:39 AM",
          "moon_phase": "First Quarter",
          "moon_illumination": "54"
        },
        "hour": [
          {
            "time_epoch": 1654552800,
            "time": "2022-06-07 00:00",
            "temp_c": 15.2,
            "temp_f": 59.4,
            "is_day": 0,
            "condition": {
              "text": "Cielo cubierto",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 242,
            "wind_dir": "WSW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 100,
            "feelslike_c": 15.2,
            "feelslike_f": 59.4,
            "windchill_c": 15.2,
            "windchill_f": 59.4,
            "heatindex_c": 15.2,
            "heatindex_f": 59.4,
            "dewpoint_c": 11.3,
            "dewpoint_f": 52.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 1
          },
          {
            "time_epoch": 1654556400,
            "time": "2022-06-07 01:00",
            "temp_c": 15,
            "temp_f": 59,
            "is_day": 0,
            "condition": {
              "text": "Cielo cubierto",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 234,
            "wind_dir": "SW",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 93,
            "feelslike_c": 14.6,
            "feelslike_f": 58.3,
            "windchill_c": 14.6,
            "windchill_f": 58.3,
            "heatindex_c": 15,
            "heatindex_f": 59,
            "dewpoint_c": 11.6,
            "dewpoint_f": 52.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 1
          },
          {
            "time_epoch": 1654560000,
            "time": "2022-06-07 02:00",
            "temp_c": 14.6,
            "temp_f": 58.3,
            "is_day": 0,
            "condition": {
              "text": "Nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 85,
            "cloud": 85,
            "feelslike_c": 14.3,
            "feelslike_f": 57.7,
            "windchill_c": 14.3,
            "windchill_f": 57.7,
            "heatindex_c": 14.6,
            "heatindex_f": 58.3,
            "dewpoint_c": 12.1,
            "dewpoint_f": 53.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 1
          },
          {
            "time_epoch": 1654563600,
            "time": "2022-06-07 03:00",
            "temp_c": 14.5,
            "temp_f": 58.1,
            "is_day": 0,
            "condition": {
              "text": "Cielo cubierto",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 210,
            "wind_dir": "SSW",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 100,
            "feelslike_c": 14.3,
            "feelslike_f": 57.7,
            "windchill_c": 14.3,
            "windchill_f": 57.7,
            "heatindex_c": 14.5,
            "heatindex_f": 58.1,
            "dewpoint_c": 12.5,
            "dewpoint_f": 54.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.2,
            "gust_kph": 11.5,
            "uv": 1
          },
          {
            "time_epoch": 1654567200,
            "time": "2022-06-07 04:00",
            "temp_c": 14.3,
            "temp_f": 57.7,
            "is_day": 0,
            "condition": {
              "text": "Ligeras precipitaciones",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
              "code": 1240
            },
            "wind_mph": 5.6,
            "wind_kph": 9,
            "wind_degree": 207,
            "wind_dir": "SSW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0.3,
            "precip_in": 0.01,
            "humidity": 92,
            "cloud": 100,
            "feelslike_c": 13.9,
            "feelslike_f": 57,
            "windchill_c": 13.9,
            "windchill_f": 57,
            "heatindex_c": 14.3,
            "heatindex_f": 57.7,
            "dewpoint_c": 12.9,
            "dewpoint_f": 55.2,
            "will_it_rain": 1,
            "chance_of_rain": 87,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.1,
            "gust_kph": 13,
            "uv": 1
          },
          {
            "time_epoch": 1654570800,
            "time": "2022-06-07 05:00",
            "temp_c": 14,
            "temp_f": 57.2,
            "is_day": 0,
            "condition": {
              "text": "Neblina",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
              "code": 1030
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 219,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 96,
            "cloud": 100,
            "feelslike_c": 13.3,
            "feelslike_f": 55.9,
            "windchill_c": 13.3,
            "windchill_f": 55.9,
            "heatindex_c": 14,
            "heatindex_f": 57.2,
            "dewpoint_c": 13.4,
            "dewpoint_f": 56.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 1
          },
          {
            "time_epoch": 1654574400,
            "time": "2022-06-07 06:00",
            "temp_c": 14.1,
            "temp_f": 57.4,
            "is_day": 1,
            "condition": {
              "text": "Ligeras precipitaciones",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 229,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0.2,
            "precip_in": 0.01,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 13.5,
            "feelslike_f": 56.3,
            "windchill_c": 13.5,
            "windchill_f": 56.3,
            "heatindex_c": 14.1,
            "heatindex_f": 57.4,
            "dewpoint_c": 13.1,
            "dewpoint_f": 55.6,
            "will_it_rain": 1,
            "chance_of_rain": 84,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 3
          },
          {
            "time_epoch": 1654578000,
            "time": "2022-06-07 07:00",
            "temp_c": 14.4,
            "temp_f": 57.9,
            "is_day": 1,
            "condition": {
              "text": "Cielo cubierto",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 233,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 90,
            "cloud": 89,
            "feelslike_c": 13.8,
            "feelslike_f": 56.8,
            "windchill_c": 13.8,
            "windchill_f": 56.8,
            "heatindex_c": 14.4,
            "heatindex_f": 57.9,
            "dewpoint_c": 12.8,
            "dewpoint_f": 55,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 3
          },
          {
            "time_epoch": 1654581600,
            "time": "2022-06-07 08:00",
            "temp_c": 14.9,
            "temp_f": 58.8,
            "is_day": 1,
            "condition": {
              "text": "Nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 228,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 84,
            "feelslike_c": 14.4,
            "feelslike_f": 57.9,
            "windchill_c": 14.4,
            "windchill_f": 57.9,
            "heatindex_c": 14.9,
            "heatindex_f": 58.8,
            "dewpoint_c": 12.7,
            "dewpoint_f": 54.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.6,
            "gust_kph": 15.5,
            "uv": 3
          },
          {
            "time_epoch": 1654585200,
            "time": "2022-06-07 09:00",
            "temp_c": 16.2,
            "temp_f": 61.2,
            "is_day": 1,
            "condition": {
              "text": "Cielo cubierto",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 229,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 100,
            "feelslike_c": 16.2,
            "feelslike_f": 61.2,
            "windchill_c": 16.2,
            "windchill_f": 61.2,
            "heatindex_c": 16.2,
            "heatindex_f": 61.2,
            "dewpoint_c": 12.2,
            "dewpoint_f": 54,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.5,
            "gust_kph": 16.9,
            "uv": 4
          },
          {
            "time_epoch": 1654588800,
            "time": "2022-06-07 10:00",
            "temp_c": 16.4,
            "temp_f": 61.5,
            "is_day": 1,
            "condition": {
              "text": "Lluvia  moderada a intervalos",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 226,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 84,
            "feelslike_c": 16.4,
            "feelslike_f": 61.5,
            "windchill_c": 16.4,
            "windchill_f": 61.5,
            "heatindex_c": 16.4,
            "heatindex_f": 61.5,
            "dewpoint_c": 11.8,
            "dewpoint_f": 53.2,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.1,
            "gust_kph": 19.4,
            "uv": 4
          },
          {
            "time_epoch": 1654592400,
            "time": "2022-06-07 11:00",
            "temp_c": 18.2,
            "temp_f": 64.8,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 228,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 60,
            "cloud": 26,
            "feelslike_c": 18.2,
            "feelslike_f": 64.8,
            "windchill_c": 18.2,
            "windchill_f": 64.8,
            "heatindex_c": 18.2,
            "heatindex_f": 64.8,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 5
          },
          {
            "time_epoch": 1654596000,
            "time": "2022-06-07 12:00",
            "temp_c": 20.1,
            "temp_f": 68.2,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 234,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 53,
            "cloud": 46,
            "feelslike_c": 20.1,
            "feelslike_f": 68.2,
            "windchill_c": 20.1,
            "windchill_f": 68.2,
            "heatindex_c": 20.1,
            "heatindex_f": 68.2,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 6
          },
          {
            "time_epoch": 1654599600,
            "time": "2022-06-07 13:00",
            "temp_c": 20,
            "temp_f": 68,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 241,
            "wind_dir": "WSW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 60,
            "cloud": 53,
            "feelslike_c": 20,
            "feelslike_f": 68,
            "windchill_c": 20,
            "windchill_f": 68,
            "heatindex_c": 20,
            "heatindex_f": 68,
            "dewpoint_c": 12.1,
            "dewpoint_f": 53.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.5,
            "gust_kph": 20.2,
            "uv": 6
          },
          {
            "time_epoch": 1654603200,
            "time": "2022-06-07 14:00",
            "temp_c": 20.9,
            "temp_f": 69.6,
            "is_day": 1,
            "condition": {
              "text": "Lluvia  moderada a intervalos",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 241,
            "wind_dir": "WSW",
            "pressure_mb": 1015,
            "pressure_in": 29.97,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 57,
            "cloud": 68,
            "feelslike_c": 20.9,
            "feelslike_f": 69.6,
            "windchill_c": 20.9,
            "windchill_f": 69.6,
            "heatindex_c": 20.9,
            "heatindex_f": 69.6,
            "dewpoint_c": 12,
            "dewpoint_f": 53.6,
            "will_it_rain": 0,
            "chance_of_rain": 66,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.4,
            "gust_kph": 18.4,
            "uv": 5
          },
          {
            "time_epoch": 1654606800,
            "time": "2022-06-07 15:00",
            "temp_c": 21.6,
            "temp_f": 70.9,
            "is_day": 1,
            "condition": {
              "text": "Lluvia  moderada a intervalos",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 248,
            "wind_dir": "WSW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 54,
            "cloud": 93,
            "feelslike_c": 21.6,
            "feelslike_f": 70.9,
            "windchill_c": 21.6,
            "windchill_f": 70.9,
            "heatindex_c": 24.4,
            "heatindex_f": 75.9,
            "dewpoint_c": 11.8,
            "dewpoint_f": 53.2,
            "will_it_rain": 1,
            "chance_of_rain": 81,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.5,
            "gust_kph": 16.9,
            "uv": 5
          },
          {
            "time_epoch": 1654610400,
            "time": "2022-06-07 16:00",
            "temp_c": 21.9,
            "temp_f": 71.4,
            "is_day": 1,
            "condition": {
              "text": "Ligeras precipitaciones",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 253,
            "wind_dir": "WSW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0.3,
            "precip_in": 0.01,
            "humidity": 53,
            "cloud": 87,
            "feelslike_c": 21.9,
            "feelslike_f": 71.4,
            "windchill_c": 21.9,
            "windchill_f": 71.4,
            "heatindex_c": 24.5,
            "heatindex_f": 76.1,
            "dewpoint_c": 12,
            "dewpoint_f": 53.6,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 5
          },
          {
            "time_epoch": 1654614000,
            "time": "2022-06-07 17:00",
            "temp_c": 19.6,
            "temp_f": 67.3,
            "is_day": 1,
            "condition": {
              "text": "Lluvia  moderada a intervalos",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 260,
            "wind_dir": "W",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0.2,
            "precip_in": 0.01,
            "humidity": 72,
            "cloud": 79,
            "feelslike_c": 19.6,
            "feelslike_f": 67.3,
            "windchill_c": 19.6,
            "windchill_f": 67.3,
            "heatindex_c": 19.6,
            "heatindex_f": 67.3,
            "dewpoint_c": 14.4,
            "dewpoint_f": 57.9,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 14.5,
            "gust_kph": 23.4,
            "uv": 4
          },
          {
            "time_epoch": 1654617600,
            "time": "2022-06-07 18:00",
            "temp_c": 18.8,
            "temp_f": 65.8,
            "is_day": 1,
            "condition": {
              "text": "Lluvia  moderada a intervalos",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 270,
            "wind_dir": "W",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0.3,
            "precip_in": 0.01,
            "humidity": 81,
            "cloud": 78,
            "feelslike_c": 18.8,
            "feelslike_f": 65.8,
            "windchill_c": 18.8,
            "windchill_f": 65.8,
            "heatindex_c": 18.8,
            "heatindex_f": 65.8,
            "dewpoint_c": 15.5,
            "dewpoint_f": 59.9,
            "will_it_rain": 0,
            "chance_of_rain": 53,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 14.8,
            "gust_kph": 23.8,
            "uv": 4
          },
          {
            "time_epoch": 1654621200,
            "time": "2022-06-07 19:00",
            "temp_c": 18.3,
            "temp_f": 64.9,
            "is_day": 1,
            "condition": {
              "text": "Lluvia  moderada a intervalos",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 284,
            "wind_dir": "WNW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0.9,
            "precip_in": 0.04,
            "humidity": 83,
            "cloud": 83,
            "feelslike_c": 18.3,
            "feelslike_f": 64.9,
            "windchill_c": 18.3,
            "windchill_f": 64.9,
            "heatindex_c": 18.3,
            "heatindex_f": 64.9,
            "dewpoint_c": 15.3,
            "dewpoint_f": 59.5,
            "will_it_rain": 0,
            "chance_of_rain": 58,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 13.2,
            "gust_kph": 21.2,
            "uv": 4
          },
          {
            "time_epoch": 1654624800,
            "time": "2022-06-07 20:00",
            "temp_c": 17,
            "temp_f": 62.6,
            "is_day": 1,
            "condition": {
              "text": "Soleado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 295,
            "wind_dir": "WNW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 15,
            "feelslike_c": 17,
            "feelslike_f": 62.6,
            "windchill_c": 17,
            "windchill_f": 62.6,
            "heatindex_c": 17,
            "heatindex_f": 62.6,
            "dewpoint_c": 14.2,
            "dewpoint_f": 57.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 5
          },
          {
            "time_epoch": 1654628400,
            "time": "2022-06-07 21:00",
            "temp_c": 15.7,
            "temp_f": 60.3,
            "is_day": 1,
            "condition": {
              "text": "Soleado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 294,
            "wind_dir": "WNW",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 11,
            "feelslike_c": 15.7,
            "feelslike_f": 60.3,
            "windchill_c": 15.7,
            "windchill_f": 60.3,
            "heatindex_c": 15.7,
            "heatindex_f": 60.3,
            "dewpoint_c": 13.6,
            "dewpoint_f": 56.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 5
          },
          {
            "time_epoch": 1654632000,
            "time": "2022-06-07 22:00",
            "temp_c": 15.3,
            "temp_f": 59.5,
            "is_day": 0,
            "condition": {
              "text": "Despejado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 272,
            "wind_dir": "W",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 14,
            "feelslike_c": 15.3,
            "feelslike_f": 59.5,
            "windchill_c": 15.3,
            "windchill_f": 59.5,
            "heatindex_c": 15.3,
            "heatindex_f": 59.5,
            "dewpoint_c": 13.4,
            "dewpoint_f": 56.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.9,
            "gust_kph": 7.9,
            "uv": 1
          },
          {
            "time_epoch": 1654635600,
            "time": "2022-06-07 23:00",
            "temp_c": 15.1,
            "temp_f": 59.2,
            "is_day": 0,
            "condition": {
              "text": "Despejado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 233,
            "wind_dir": "SW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 89,
            "cloud": 11,
            "feelslike_c": 15.1,
            "feelslike_f": 59.2,
            "windchill_c": 15.1,
            "windchill_f": 59.2,
            "heatindex_c": 15.1,
            "heatindex_f": 59.2,
            "dewpoint_c": 13.2,
            "dewpoint_f": 55.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.9,
            "gust_kph": 7.9,
            "uv": 1
          }
        ]
      },
      {
        "date": "2022-06-08",
        "date_epoch": 1654646400,
        "day": {
          "maxtemp_c": 21.5,
          "maxtemp_f": 70.7,
          "mintemp_c": 13.1,
          "mintemp_f": 55.6,
          "avgtemp_c": 16,
          "avgtemp_f": 60.8,
          "maxwind_mph": 12.5,
          "maxwind_kph": 20.2,
          "totalprecip_mm": 11.5,
          "totalprecip_in": 0.45,
          "avgvis_km": 9.4,
          "avgvis_miles": 5,
          "avghumidity": 80,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 86,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Lluvia moderada",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
            "code": 1189
          },
          "uv": 5
        },
        "astro": {
          "sunrise": "05:48 AM",
          "sunset": "09:52 PM",
          "moonrise": "02:23 PM",
          "moonset": "02:56 AM",
          "moon_phase": "First Quarter",
          "moon_illumination": "61"
        },
        "hour": [
          {
            "time_epoch": 1654639200,
            "time": "2022-06-08 00:00",
            "temp_c": 14.5,
            "temp_f": 58.1,
            "is_day": 0,
            "condition": {
              "text": "Despejado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 201,
            "wind_dir": "SSW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 89,
            "cloud": 10,
            "feelslike_c": 14.8,
            "feelslike_f": 58.6,
            "windchill_c": 14.8,
            "windchill_f": 58.6,
            "heatindex_c": 14.5,
            "heatindex_f": 58.1,
            "dewpoint_c": 12.7,
            "dewpoint_f": 54.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 1
          },
          {
            "time_epoch": 1654642800,
            "time": "2022-06-08 01:00",
            "temp_c": 14.2,
            "temp_f": 57.6,
            "is_day": 0,
            "condition": {
              "text": "Despejado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 200,
            "wind_dir": "SSW",
            "pressure_mb": 1015,
            "pressure_in": 29.97,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 90,
            "cloud": 18,
            "feelslike_c": 14.1,
            "feelslike_f": 57.4,
            "windchill_c": 14.1,
            "windchill_f": 57.4,
            "heatindex_c": 14.2,
            "heatindex_f": 57.6,
            "dewpoint_c": 12.6,
            "dewpoint_f": 54.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.1,
            "gust_kph": 13,
            "uv": 1
          },
          {
            "time_epoch": 1654646400,
            "time": "2022-06-08 02:00",
            "temp_c": 13.9,
            "temp_f": 57,
            "is_day": 0,
            "condition": {
              "text": "Despejado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 189,
            "wind_dir": "S",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 90,
            "cloud": 20,
            "feelslike_c": 13.5,
            "feelslike_f": 56.3,
            "windchill_c": 13.5,
            "windchill_f": 56.3,
            "heatindex_c": 13.9,
            "heatindex_f": 57,
            "dewpoint_c": 12.3,
            "dewpoint_f": 54.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 1
          },
          {
            "time_epoch": 1654650000,
            "time": "2022-06-08 03:00",
            "temp_c": 13.6,
            "temp_f": 56.5,
            "is_day": 0,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 205,
            "wind_dir": "SSW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 44,
            "feelslike_c": 13,
            "feelslike_f": 55.4,
            "windchill_c": 13,
            "windchill_f": 55.4,
            "heatindex_c": 13.6,
            "heatindex_f": 56.5,
            "dewpoint_c": 11.6,
            "dewpoint_f": 52.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 1
          },
          {
            "time_epoch": 1654653600,
            "time": "2022-06-08 04:00",
            "temp_c": 13.3,
            "temp_f": 55.9,
            "is_day": 0,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 204,
            "wind_dir": "SSW",
            "pressure_mb": 1014,
            "pressure_in": 29.93,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 48,
            "feelslike_c": 12.6,
            "feelslike_f": 54.7,
            "windchill_c": 12.6,
            "windchill_f": 54.7,
            "heatindex_c": 13.3,
            "heatindex_f": 55.9,
            "dewpoint_c": 11.1,
            "dewpoint_f": 52,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.5,
            "gust_kph": 16.9,
            "uv": 1
          },
          {
            "time_epoch": 1654657200,
            "time": "2022-06-08 05:00",
            "temp_c": 13.4,
            "temp_f": 56.1,
            "is_day": 0,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 199,
            "wind_dir": "SSW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 54,
            "feelslike_c": 12.6,
            "feelslike_f": 54.7,
            "windchill_c": 12.6,
            "windchill_f": 54.7,
            "heatindex_c": 13.4,
            "heatindex_f": 56.1,
            "dewpoint_c": 10.7,
            "dewpoint_f": 51.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1654660800,
            "time": "2022-06-08 06:00",
            "temp_c": 13.7,
            "temp_f": 56.7,
            "is_day": 1,
            "condition": {
              "text": "Cielo cubierto",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 203,
            "wind_dir": "SSW",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 84,
            "cloud": 100,
            "feelslike_c": 12.7,
            "feelslike_f": 54.9,
            "windchill_c": 12.7,
            "windchill_f": 54.9,
            "heatindex_c": 13.7,
            "heatindex_f": 56.7,
            "dewpoint_c": 11,
            "dewpoint_f": 51.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.3,
            "gust_kph": 19.8,
            "uv": 3
          },
          {
            "time_epoch": 1654664400,
            "time": "2022-06-08 07:00",
            "temp_c": 13.1,
            "temp_f": 55.6,
            "is_day": 1,
            "condition": {
              "text": "Cielo cubierto",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 199,
            "wind_dir": "SSW",
            "pressure_mb": 1012,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 11.9,
            "feelslike_f": 53.4,
            "windchill_c": 11.9,
            "windchill_f": 53.4,
            "heatindex_c": 13.1,
            "heatindex_f": 55.6,
            "dewpoint_c": 12.2,
            "dewpoint_f": 54,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.8,
            "gust_kph": 20.5,
            "uv": 3
          },
          {
            "time_epoch": 1654668000,
            "time": "2022-06-08 08:00",
            "temp_c": 13.1,
            "temp_f": 55.6,
            "is_day": 1,
            "condition": {
              "text": "Lluvia moderada",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 189,
            "wind_dir": "S",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 3.1,
            "precip_in": 0.12,
            "humidity": 97,
            "cloud": 100,
            "feelslike_c": 11.8,
            "feelslike_f": 53.2,
            "windchill_c": 11.8,
            "windchill_f": 53.2,
            "heatindex_c": 13.1,
            "heatindex_f": 55.6,
            "dewpoint_c": 12.6,
            "dewpoint_f": 54.7,
            "will_it_rain": 0,
            "chance_of_rain": 64,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 7,
            "vis_miles": 4,
            "gust_mph": 13.4,
            "gust_kph": 21.6,
            "uv": 3
          },
          {
            "time_epoch": 1654671600,
            "time": "2022-06-08 09:00",
            "temp_c": 13.7,
            "temp_f": 56.7,
            "is_day": 1,
            "condition": {
              "text": "Ligeras lluvias",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
              "code": 1183
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 202,
            "wind_dir": "SSW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 1.7,
            "precip_in": 0.07,
            "humidity": 97,
            "cloud": 100,
            "feelslike_c": 12.4,
            "feelslike_f": 54.3,
            "windchill_c": 12.4,
            "windchill_f": 54.3,
            "heatindex_c": 13.7,
            "heatindex_f": 56.7,
            "dewpoint_c": 13.2,
            "dewpoint_f": 55.8,
            "will_it_rain": 0,
            "chance_of_rain": 64,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 3
          },
          {
            "time_epoch": 1654675200,
            "time": "2022-06-08 10:00",
            "temp_c": 14.2,
            "temp_f": 57.6,
            "is_day": 1,
            "condition": {
              "text": "Lluvia moderada",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 209,
            "wind_dir": "SSW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 4.2,
            "precip_in": 0.17,
            "humidity": 97,
            "cloud": 100,
            "feelslike_c": 13.1,
            "feelslike_f": 55.6,
            "windchill_c": 13.1,
            "windchill_f": 55.6,
            "heatindex_c": 14.2,
            "heatindex_f": 57.6,
            "dewpoint_c": 13.7,
            "dewpoint_f": 56.7,
            "will_it_rain": 0,
            "chance_of_rain": 70,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 7,
            "vis_miles": 4,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 3
          },
          {
            "time_epoch": 1654678800,
            "time": "2022-06-08 11:00",
            "temp_c": 15.5,
            "temp_f": 59.9,
            "is_day": 1,
            "condition": {
              "text": "Llovizna",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 210,
            "wind_dir": "SSW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0.2,
            "precip_in": 0.01,
            "humidity": 95,
            "cloud": 100,
            "feelslike_c": 15.5,
            "feelslike_f": 59.9,
            "windchill_c": 15.5,
            "windchill_f": 59.9,
            "heatindex_c": 15.5,
            "heatindex_f": 59.9,
            "dewpoint_c": 14.7,
            "dewpoint_f": 58.5,
            "will_it_rain": 0,
            "chance_of_rain": 65,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 13.6,
            "gust_kph": 22,
            "uv": 4
          },
          {
            "time_epoch": 1654682400,
            "time": "2022-06-08 12:00",
            "temp_c": 16.3,
            "temp_f": 61.3,
            "is_day": 1,
            "condition": {
              "text": "Ligeras precipitaciones",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 222,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 0.9,
            "precip_in": 0.04,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 16.3,
            "feelslike_f": 61.3,
            "windchill_c": 16.3,
            "windchill_f": 61.3,
            "heatindex_c": 16.3,
            "heatindex_f": 61.3,
            "dewpoint_c": 15.3,
            "dewpoint_f": 59.5,
            "will_it_rain": 1,
            "chance_of_rain": 75,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13,
            "gust_kph": 20.9,
            "uv": 4
          },
          {
            "time_epoch": 1654686000,
            "time": "2022-06-08 13:00",
            "temp_c": 17.6,
            "temp_f": 63.7,
            "is_day": 1,
            "condition": {
              "text": "Nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 228,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 87,
            "feelslike_c": 17.6,
            "feelslike_f": 63.7,
            "windchill_c": 17.6,
            "windchill_f": 63.7,
            "heatindex_c": 17.6,
            "heatindex_f": 63.7,
            "dewpoint_c": 15.3,
            "dewpoint_f": 59.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 4
          },
          {
            "time_epoch": 1654689600,
            "time": "2022-06-08 14:00",
            "temp_c": 19.4,
            "temp_f": 66.9,
            "is_day": 1,
            "condition": {
              "text": "Ligeras precipitaciones",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 247,
            "wind_dir": "WSW",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0.4,
            "precip_in": 0.02,
            "humidity": 77,
            "cloud": 60,
            "feelslike_c": 19.4,
            "feelslike_f": 66.9,
            "windchill_c": 19.4,
            "windchill_f": 66.9,
            "heatindex_c": 19.4,
            "heatindex_f": 66.9,
            "dewpoint_c": 15.2,
            "dewpoint_f": 59.4,
            "will_it_rain": 1,
            "chance_of_rain": 81,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.1,
            "gust_kph": 19.4,
            "uv": 4
          },
          {
            "time_epoch": 1654693200,
            "time": "2022-06-08 15:00",
            "temp_c": 21.5,
            "temp_f": 70.7,
            "is_day": 1,
            "condition": {
              "text": "Ligeras precipitaciones",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 11.6,
            "wind_kph": 18.7,
            "wind_degree": 262,
            "wind_dir": "W",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0.3,
            "precip_in": 0.01,
            "humidity": 58,
            "cloud": 63,
            "feelslike_c": 21.5,
            "feelslike_f": 70.7,
            "windchill_c": 21.5,
            "windchill_f": 70.7,
            "heatindex_c": 24.5,
            "heatindex_f": 76.1,
            "dewpoint_c": 12.9,
            "dewpoint_f": 55.2,
            "will_it_rain": 1,
            "chance_of_rain": 86,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.3,
            "gust_kph": 23,
            "uv": 5
          },
          {
            "time_epoch": 1654696800,
            "time": "2022-06-08 16:00",
            "temp_c": 21.3,
            "temp_f": 70.3,
            "is_day": 1,
            "condition": {
              "text": "Ligeras precipitaciones",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 266,
            "wind_dir": "W",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0.6,
            "precip_in": 0.02,
            "humidity": 53,
            "cloud": 61,
            "feelslike_c": 21.3,
            "feelslike_f": 70.3,
            "windchill_c": 21.3,
            "windchill_f": 70.3,
            "heatindex_c": 24.4,
            "heatindex_f": 75.9,
            "dewpoint_c": 11.5,
            "dewpoint_f": 52.7,
            "will_it_rain": 0,
            "chance_of_rain": 66,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.3,
            "gust_kph": 26.3,
            "uv": 5
          },
          {
            "time_epoch": 1654700400,
            "time": "2022-06-08 17:00",
            "temp_c": 20.4,
            "temp_f": 68.7,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 267,
            "wind_dir": "W",
            "pressure_mb": 1012,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 55,
            "cloud": 52,
            "feelslike_c": 20.4,
            "feelslike_f": 68.7,
            "windchill_c": 20.4,
            "windchill_f": 68.7,
            "heatindex_c": 20.4,
            "heatindex_f": 68.7,
            "dewpoint_c": 11.1,
            "dewpoint_f": 52,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.1,
            "gust_kph": 25.9,
            "uv": 6
          },
          {
            "time_epoch": 1654704000,
            "time": "2022-06-08 18:00",
            "temp_c": 19.2,
            "temp_f": 66.6,
            "is_day": 1,
            "condition": {
              "text": "Lluvia  moderada a intervalos",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 272,
            "wind_dir": "W",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0.1,
            "precip_in": 0,
            "humidity": 61,
            "cloud": 89,
            "feelslike_c": 19.2,
            "feelslike_f": 66.6,
            "windchill_c": 19.2,
            "windchill_f": 66.6,
            "heatindex_c": 19.2,
            "heatindex_f": 66.6,
            "dewpoint_c": 11.5,
            "dewpoint_f": 52.7,
            "will_it_rain": 1,
            "chance_of_rain": 73,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.9,
            "gust_kph": 25.6,
            "uv": 4
          },
          {
            "time_epoch": 1654707600,
            "time": "2022-06-08 19:00",
            "temp_c": 18.7,
            "temp_f": 65.7,
            "is_day": 1,
            "condition": {
              "text": "Soleado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.8,
            "wind_kph": 15.8,
            "wind_degree": 280,
            "wind_dir": "W",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 62,
            "cloud": 25,
            "feelslike_c": 18.7,
            "feelslike_f": 65.7,
            "windchill_c": 18.7,
            "windchill_f": 65.7,
            "heatindex_c": 18.7,
            "heatindex_f": 65.7,
            "dewpoint_c": 11.3,
            "dewpoint_f": 52.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.6,
            "gust_kph": 22,
            "uv": 5
          },
          {
            "time_epoch": 1654711200,
            "time": "2022-06-08 20:00",
            "temp_c": 17.4,
            "temp_f": 63.3,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 289,
            "wind_dir": "WNW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 66,
            "cloud": 46,
            "feelslike_c": 17.4,
            "feelslike_f": 63.3,
            "windchill_c": 17.4,
            "windchill_f": 63.3,
            "heatindex_c": 17.4,
            "heatindex_f": 63.3,
            "dewpoint_c": 11,
            "dewpoint_f": 51.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.8,
            "gust_kph": 20.5,
            "uv": 5
          },
          {
            "time_epoch": 1654714800,
            "time": "2022-06-08 21:00",
            "temp_c": 16,
            "temp_f": 60.8,
            "is_day": 1,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 291,
            "wind_dir": "WNW",
            "pressure_mb": 1015,
            "pressure_in": 29.97,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 72,
            "cloud": 54,
            "feelslike_c": 16,
            "feelslike_f": 60.8,
            "windchill_c": 16,
            "windchill_f": 60.8,
            "heatindex_c": 16,
            "heatindex_f": 60.8,
            "dewpoint_c": 11,
            "dewpoint_f": 51.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.1,
            "gust_kph": 13,
            "uv": 5
          },
          {
            "time_epoch": 1654718400,
            "time": "2022-06-08 22:00",
            "temp_c": 15.2,
            "temp_f": 59.4,
            "is_day": 0,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 271,
            "wind_dir": "W",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 76,
            "cloud": 46,
            "feelslike_c": 15.2,
            "feelslike_f": 59.4,
            "windchill_c": 15.2,
            "windchill_f": 59.4,
            "heatindex_c": 15.2,
            "heatindex_f": 59.4,
            "dewpoint_c": 11.1,
            "dewpoint_f": 52,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6,
            "gust_kph": 9.7,
            "uv": 1
          },
          {
            "time_epoch": 1654722000,
            "time": "2022-06-08 23:00",
            "temp_c": 15,
            "temp_f": 59,
            "is_day": 0,
            "condition": {
              "text": "Parcialmente nublado",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 268,
            "wind_dir": "W",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 78,
            "cloud": 51,
            "feelslike_c": 15.2,
            "feelslike_f": 59.4,
            "windchill_c": 15.2,
            "windchill_f": 59.4,
            "heatindex_c": 15,
            "heatindex_f": 59,
            "dewpoint_c": 11.2,
            "dewpoint_f": 52.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 1
          }
        ]
      }
    ]
  }
}